[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "mach_o_sys"
description = "Bindings to the OSX mach-o system library"
version = "0.1.1"
license = "Apache-2.0/MIT"
keywords = ["mach", "macho", "mach-o"]
repository = "https://github.com/fitzgen/mach_o_sys"

[dependencies]
