[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
description = "Bindings to the OSX mach-o system library"
keywords = ["mach", "macho", "mach-o"]
license = "Apache-2.0/MIT"
name = "mach_o_sys"
repository = "https://github.com/fitzgen/mach_o_sys"
version = "0.1.1"

[dependencies]
