/* automatically generated by rust-bindgen 0.70.1 */

#![allow(
    dead_code,
    non_camel_case_types,
    non_upper_case_globals,
    non_snake_case
)]

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum reloc_type_arm {
    ARM_RELOC_VANILLA = 0,
    ARM_RELOC_PAIR = 1,
    ARM_RELOC_SECTDIFF = 2,
    ARM_RELOC_LOCAL_SECTDIFF = 3,
    ARM_RELOC_PB_LA_PTR = 4,
    ARM_RELOC_BR24 = 5,
    ARM_THUMB_RELOC_BR22 = 6,
    ARM_THUMB_32BIT_BRANCH = 7,
    ARM_RELOC_HALF = 8,
    ARM_RELOC_HALF_SECTDIFF = 9,
}
