/* automatically generated by rust-bindgen 0.70.1 */

#![allow(
    dead_code,
    non_camel_case_types,
    non_upper_case_globals,
    non_snake_case
)]
use crate::loader::*;

extern "C" {
    pub fn getsectdata(
        segname: *const ::std::os::raw::c_char,
        sectname: *const ::std::os::raw::c_char,
        size: *mut ::std::os::raw::c_ulong,
    ) -> *mut ::std::os::raw::c_char;
    pub fn getsectdatafromFramework(
        FrameworkName: *const ::std::os::raw::c_char,
        segname: *const ::std::os::raw::c_char,
        sectname: *const ::std::os::raw::c_char,
        size: *mut ::std::os::raw::c_ulong,
    ) -> *mut ::std::os::raw::c_char;
    pub fn get_end() -> ::std::os::raw::c_ulong;
    pub fn get_etext() -> ::std::os::raw::c_ulong;
    pub fn get_edata() -> ::std::os::raw::c_ulong;
    pub fn getsectbyname(
        segname: *const ::std::os::raw::c_char,
        sectname: *const ::std::os::raw::c_char,
    ) -> *const section_64;
    pub fn getsectiondata(
        mhp: *const mach_header_64,
        segname: *const ::std::os::raw::c_char,
        sectname: *const ::std::os::raw::c_char,
        size: *mut ::std::os::raw::c_ulong,
    ) -> *mut u8;
    pub fn getsegbyname(segname: *const ::std::os::raw::c_char) -> *const segment_command_64;
    pub fn getsegmentdata(
        mhp: *const mach_header_64,
        segname: *const ::std::os::raw::c_char,
        size: *mut ::std::os::raw::c_ulong,
    ) -> *mut u8;
    pub fn getsectdatafromheader(
        mhp: *const mach_header,
        segname: *const ::std::os::raw::c_char,
        sectname: *const ::std::os::raw::c_char,
        size: *mut u32,
    ) -> *mut ::std::os::raw::c_char;
    pub fn getsectbynamefromheader(
        mhp: *const mach_header,
        segname: *const ::std::os::raw::c_char,
        sectname: *const ::std::os::raw::c_char,
    ) -> *const section;
    pub fn getsectbynamefromheaderwithswap(
        mhp: *mut mach_header,
        segname: *const ::std::os::raw::c_char,
        sectname: *const ::std::os::raw::c_char,
        fSwap: ::std::os::raw::c_int,
    ) -> *const section;
    pub fn getsectdatafromheader_64(
        mhp: *const mach_header_64,
        segname: *const ::std::os::raw::c_char,
        sectname: *const ::std::os::raw::c_char,
        size: *mut u64,
    ) -> *mut ::std::os::raw::c_char;
    pub fn getsectbynamefromheader_64(
        mhp: *const mach_header_64,
        segname: *const ::std::os::raw::c_char,
        sectname: *const ::std::os::raw::c_char,
    ) -> *const section_64;
    pub fn getsectbynamefromheaderwithswap_64(
        mhp: *mut mach_header_64,
        segname: *const ::std::os::raw::c_char,
        sectname: *const ::std::os::raw::c_char,
        fSwap: ::std::os::raw::c_int,
    ) -> *const section;
}
