/* automatically generated by rust-bindgen 0.70.1 */

#![allow(
    dead_code,
    non_camel_case_types,
    non_upper_case_globals,
    non_snake_case
)]

pub const N_GSYM: u32 = 32;
pub const N_FNAME: u32 = 34;
pub const N_FUN: u32 = 36;
pub const N_STSYM: u32 = 38;
pub const N_LCSYM: u32 = 40;
pub const N_BNSYM: u32 = 46;
pub const N_AST: u32 = 50;
pub const N_OPT: u32 = 60;
pub const N_RSYM: u32 = 64;
pub const N_SLINE: u32 = 68;
pub const N_ENSYM: u32 = 78;
pub const N_SSYM: u32 = 96;
pub const N_SO: u32 = 100;
pub const N_OSO: u32 = 102;
pub const N_LIB: u32 = 104;
pub const N_LSYM: u32 = 128;
pub const N_BINCL: u32 = 130;
pub const N_SOL: u32 = 132;
pub const N_PARAMS: u32 = 134;
pub const N_VERSION: u32 = 136;
pub const N_OLEVEL: u32 = 138;
pub const N_PSYM: u32 = 160;
pub const N_EINCL: u32 = 162;
pub const N_ENTRY: u32 = 164;
pub const N_LBRAC: u32 = 192;
pub const N_EXCL: u32 = 194;
pub const N_RBRAC: u32 = 224;
pub const N_BCOMM: u32 = 226;
pub const N_ECOMM: u32 = 228;
pub const N_ECOML: u32 = 232;
pub const N_LENG: u32 = 254;
pub const N_PC: u32 = 48;
